### ISSUE TITLE
GroupConsumer does not support starting group at offset 0

### ISSUE THREAD

**Issue by steve-gray** [oleksiyk/kafka#1]
Hello,

I've noticed when adding new GroupConsumers to a topic for watching, they start watching from the current position of the topic and not the start position. This means only new data from the time the consumer is added is reported on, which is often not the requirement (i.e. Adding a new consumer to read a log from start to finish, and then watch the tail).

Is there a flag or option to make the initial offset be 0 for a new consumer?

-Steve

**Comment by oleksiyk** [comment]
So, as described in #2 I can't accept your PR. But this issue can be solved with two proposed options: #3 and #4. I prefer #4.

**Comment by oleksiyk** [comment]
But for now the new [startingOffset](https://github.com/oleksiyk/kafka/commit/7339ce0ad269fd518e3dba92116b350330205714) option will do.

**Comment by oleksiyk** [comment]
Fixed in 0.1.5
