### ISSUE TITLE
Topic Creation/Management API's

### ISSUE THREAD

**Issue by steve-gray** [oleksiyk/kafka#10]
Request for some API's for topic introspection and management, such as:

- Creation
- Partition management
- Compaction
- Viewing state of broker farm.

Or do you feel that no-kafka is more a consumption/production solution? Interested in what the roadmap might be.

**Comment by oleksiyk** [comment]
I'm afraid some or all of these features are out of pure client possibilities. For example there is no way to create topics. There is a Kafka server option `auto.create.topics.enable, true` but there is no API call to create partitions. 
Partition management and other requested features will require Zookeeper connection and knowledge of internal Kafka setup. 

Have a look at https://github.com/yahoo/kafka-manager.

**Comment by oleksiyk** [comment]
For some kind of broker farm inspection have a look at `GroupConsumer.listGroups` and `GroupConsumer.describeGroup`. These are the only management APIs exposed by Kafka server.

**Comment by steve-gray** [comment]
I was guessing it'd require ZooKeeper integration: maybe it is best to keep anything ZK related in a seperate module - the purity of this one around the produce/consume side is nice as it is. Those other two API's for listing the groups/describing group: is there a way to see get the per-partition offsets and last seen time for consumers from those? I'm just wondering if I can see the detail needed for a dashboard that way without having to join the group as a worker.

**Comment by oleksiyk** [comment]
Yes, you can get committed offsets (not time) with `GroupConsumer.fetchOffset` API:

```javascript
return consumer.fetchOffset([
    {topic: 'kafka-test-topic', partition: 0},
    {topic: 'kafka-test-topic', partition: 1},
    {topic: 'kafka-test-topic', partition: 2}
])
.then(function (reply) {
    /*
    [ { topic: 'kafka-test-topic',
        partition: 0,
        offset: 264,
        metadata: null,
        error: null },
      { topic: 'kafka-test-topic',
        partition: 1,
        offset: 88,
        metadata: null,
        error: null },
      { topic: 'kafka-test-topic',
        partition: 2,
        offset: 84,
        metadata: null,
        error: null } ]
     */
})
```

**Comment by oleksiyk** [comment]
But you are right, you'll need to join the group for this. Its not hard to move these APIs into a separate code instance, like Admin or something.

**Comment by oleksiyk** [comment]
`listGroups` and `describeGroup` are now parts of `Kafka.GroupAdmin`. I will publish new npm version soon.
