### ISSUE TITLE
Error Reading Compressed Data?

### ISSUE THREAD

**Issue by steve-gray** [oleksiyk/kafka#100]
Interesting issue when using the flozano/kafka image's latest version:

      Failed to decompress message at events:49@3141 RangeError: Trying to access beyond buffer length
      RangeError: Trying to access beyond buffer length
          at _Reader.Reader.demand (/app/node_modules/module-workercore/node_modules/avrolanche/node_modules/bin-protocol/lib/reader.js:79:15)
          at _Reader.define.read (/app/node_modules/module-workercore/node_modules/avrolanche/node_modules/bin-protocol/lib/index.js:118:14)
          at _Reader._read (/app/node_modules/module-workercore/node_modules/avrolanche/node_modules/bin-protocol/lib/reader.js:42:12)
          at apply (/app/node_modules/module-workercore/node_modules/avrolanche/node_modules/lodash/lodash.js:411:27)
          at _Reader.wrapper [as raw] (/app/node_modules/gaming-module-workercore/node_modules/avrolanche/node_modules/lodash/lodash.js:4837:16)
         

Any ideas? It seems that it's failing when reading a Gzipped message from the stream because it's going 'over the end' of the buffer - potentially an issue when handling compressed messages? I've not dug too deeply into it yet - but I'm wondering if there's a semi-obvious reason that might be causing this.

Will be rebuilding the message corpus without compression when producing to see if that abates it. Was using Codec 1 (GZIP)

**Comment by oleksiyk** [comment]
Does it happen with any gzipped message or some specific?

**Comment by steve-gray** [comment]
Here's where it got a little wierder: if I set the codec to 0 (NONE) on the publisher, blow away kafka and reingest the data - I get different errors. Effectively what I'm seeing under very high load (100,000's of messages) - is that occasionally we get messages pulled out that are incomplete in the buffer.

I suspect that the issue is that under some circumstance, the data comes back either too long/short in the buffer relative to it's declared size. Is there some way for me to dump out the specific message? The data is an avro-serialzied byte buffer - and we get failures reading it back via the AVSC library. I suspect the real problem is that we get partial messages back at the tail of a fully packed buffer - and that this causes the decompression (when GZIP is on) and the deserialization (when it's just a raw buffer) to fail, because the data is incomplete.

**Comment by oleksiyk** [comment]
What is no-kafka version being used?

**Comment by steve-gray** [comment]
Tried a few: we used it with latest and also a hacked up version we made without snappy. I suspect the issue is potentially because when we start a new consumer at -2/start of log, perhaps the bulk of data overflows something. I've a theory on how to reproduce it I'll put to practice tomorrow at work.

(New Kafka, create topic, write 1m messages, then read back from offset -2, I suspect messages overflowing size of buffer is issue)

**Comment by oleksiyk** [comment]
Is that the only stack trace available?

**Comment by steve-gray** [comment]
Yes. I've had to leave things stable during the day for demonstrating some other part of the platform. I'll be working on a small-scale repro shortly.

**Comment by steve-gray** [comment]
@oleksiyk - Narrowed it down to it being the gzip stuff - it seems that we'd actually been ignoring the codec flag and manually setting it to 1, so everything was gzipped synchronously.

**Comment by steve-gray** [comment]
Closing: I suspect there's something here, but we've switched off compression for the time being and I'm not in a position to reproduce.
