### ISSUE TITLE
Why does GroupConsumer.init succeed when the topic does not exist?

### ISSUE THREAD

**Issue by Mattenable** [oleksiyk/kafka#106]
A error is logged like `Sync group: unknown topic: invalid-topic-name` but the call to init succeeds

**Comment by oleksiyk** [comment]
Because a single missing topic is not considered as fatal error.

**Comment by Mattenable** [comment]
It still succeeds if all topics are missing. The consumer cannot do anything at that point.

**Comment by oleksiyk** [comment]
Unknown topic (one or all) is not considered as fatal error for group consumer in no-kafka.
