### ISSUE TITLE
3.x release or SSL in 2.x?

### ISSUE THREAD

**Issue by hunterloftis** [oleksiyk/kafka#112]
The Heroku Kafka CLI has been running with this patched 2.x branch (patch adds SSL support):
- https://github.com/hunterloftis/kafka

We would love to get the CLI pointed back at this official lib, but can't without either SSL in 2.x or with the SSL in the unreleased 3.x branch.

Are there features slowing down the 3.x release? If so, and you can describe them, we may be able to help expedite that branch. Alternatively, what do you think of merging SSL into the next 2.x release? Currently, with neither of those complete, no version of no-kafka supports secure connections.

**Comment by p-thorpe** [comment]
@hunterloftis I was wondering the same thing in #110.
I've been porting some of the SSL changes from the `3.0` branch into my fork if you wanted to take a look.
I was also aiming to add SASL PLAIN which would require 10.0, but maybe they could be delivered separately.

**Comment by ghermeto** [comment]
Hi @oleksiyk. Any chance of releasing SSL in 2.X? I have been using branch 3.X without problems, but we would like to use the latest NPM release to keep up to date with bug fixes.

**Comment by oleksiyk** [comment]
I think I'll just release 3.0. Without full support for Kafka 10.0

**Comment by ghermeto** [comment]
Hi @oleksiyk, are you still planning to release 3.0 without full 0.10 support? Thanks.

**Comment by thody** [comment]
Is there anything we can do to help get a release out with SSL support? Would just like to know what barriers exist so we can support you however possible and expedite things.

**Comment by oleksiyk** [comment]
I've published version 3.0.0. Sorry everyone for the huge delay.
