### ISSUE TITLE
Potential Feature / Remap Broker Connections

### ISSUE THREAD

**Issue by steve-gray** [oleksiyk/kafka#113]
Hey @oleksiyk,

Wanted to get your feedback before I submit a PR. I'm thinking to add some code to allow remapping the addresses returned from Kafka for the broker connections for cases where sometimes the Kafka advertised name isn't appropriate for a client.

My usage case/scenario is basically:

- Kafka is running inside a PaaS type setup, where it's name is 'kafka-broker-0x' and apps are talking to those brokers, using virtual DNS (i.e. Rancher/Kubenetes etc)
- A client outside the environment cannot communicate with the cluster because whilst the initial connection might survive the NAT, the subsequent reconnection to individual brokers will die.

What's proposed 

- Change the parameters for SimpleConsumer, GroupAdmin, Producer, GroupConsumer to accept a new  parameter that allows for remapping of host values, `brokerRedirection`:

    {
      "brokerRedirection": {
        "host-address:9092": "client-host-address:9092"
      },
     // Other options unchanged
    }
 
- The behaviour will be such that if the value is an object, the object is treated as a map for fast resolves of 'what kafka thinks' to 'what client really needs to use', to deal with non-symmetrical NAT scenarios.

- If the value is a function, the function is called with (string, int) pair of arguments for broker-name and port, and the corresponding string-return value is used instead for the socket connection to the particular broker. This allows for suffixing FQDN's, replacing values or port remapping for PaaS/IaaS setups etc.

It's hopefully a really small feature that won't pervert the core feature-set.

**Comment by oleksiyk** [comment]
This might really be useful. How about to only leave function remapping to simplify code (and drop support for object/map)? Passing a function is not much more work than passing a map. What do you think?

**Comment by steve-gray** [comment]
I was thinking that for really simple cases that the simple-map is actually preferable, and that the function is the escalation point for anything beyond the trivial.

For example, a lot of my projects use small single-broker clusters living inside a container (flozano/kafka image from hub). In that scenario you can do the entire internal/external remap with a static config file and environment variables (a-la the NPMJS 'config' package). Passing a function to it is actually a lot harder in that scenario. When you get to complex, dynamically scaling clusters - this won't fly, but that's where you break out a function.

I'm just banging out the last of the kinks now - Node 0.1 hates me.

**Comment by steve-gray** [comment]
Build passing. Please squash the commits if you take this one in 😬

**Comment by oleksiyk** [comment]
Thanks!
