### ISSUE TITLE
Minimum Kafka log offset

### ISSUE THREAD

**Issue by Black-Star** [oleksiyk/kafka#118]
Why kafka lag is 1 not 0?
By using kafka-offset checker I have checked lag
Group           Topic           Pid Offset          logSize         Lag             Owner
group            topic            0   21641           21642           1               none
group            topic            1   21401           21402           1               none
group            topic            2   21389           21390           1               none
group            topic            3   21418           21419           1               none

Locally I have tested with kafka-consumer locally and I got 

Group    Topic   Pid Offset     logSize       Lag             Owner
ravi        ravi       0   11              11              0               ravi_qgraph-1475161519399-ab5ee7da-0
ravi        ravi       1   10              10              0               ravi_qgraph-1475161519399-ab5ee7da-0
ravi        ravi       2   10              10              0               ravi_qgraph-1475161519399-ab5ee7da-0
ravi        ravi       3   11              11              0               ravi_qgraph-1475161519399-ab5ee7da-0

**Comment by oleksiyk** [comment]
Check your application code. Nothing to do with the library.
