### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by estliberitas** [oleksiyk/kafka#12]
Hello @oleksiyk!

I'm moving discussion from SOHU-Co/kafka-node#309 here. At least I came to thinking that author of `kafka-node` has no time or wish to re-organize his project for the good of everyone. Also I'm seeing kind of regress in code and quality of module after `0.3.0` was released. And your module seems to be very promising. So we'd like to help ya with kind of roadmap, splitting tasks, covering with tests, review, etc. Are you interested or not? :wink: 

/cc @ismriv @paddy3883

**Comment by oleksiyk** [comment]
Hi Alexander!

I'm all open for new tests, better docs and other improvements.

**Comment by oleksiyk** [comment]
As for Java library compatibility for API.. I have some concerns as I would prefer to keep things simple where possible. Like, different languages, different styles. Anyway, I'm open for discussion :)

**Comment by estliberitas** [comment]
@oleksiyk Well, there I was talking about compatibility in stuff like options and the way things are handled, meaning synchronization, etc. So Node.js Kafka client solves same tasks but using Node way. Okay, then, soon I'll come with a list of ideas.

**Comment by ismriv** [comment]
Ok, let's get more concrete. These would be the top priority for me:

**Compression**: We use Kafka in production, and use snappy compression. The driver should support none, gzip & snappy.

**Replace consumer fire & forget emitter with promise or function callback**: when you have a producer way faster than the consumer, or a topic with many many messages to be processed, the consumer will keep receiving messages without making sure they have been processed (and committed), eventually crashing the application due to memory limitations. 

    // base_consumer.js
    self.emit('data', p.messageSet, p.topic, p.partition);

    // application
    consumer.on('data', function (messageSet, topic, partition) { ... })

Committing offsets when a `messageSet` has been processed does not guarantee that previous message sets have been fully processed, and a crash of the app would mean losing messages.

My proposal is something along the lines of:

    // base_consumer.js
    self.onMessageSet(p.messageSet, p.topic, p.partition).then(function () {..});

    // application
    function onMessageSet(messageSet, topic, partition) {
       // process messages ...
       return Promise.resolve(); // the consumer would only send another fetch request after this, and it could event auto commit offsets (if configured as an option)
    });

The above is just a rough idea, but the main point is that no more fetch requests are sent to the Kafka broker until the application has acknowledge the consumption of the messages.

**Ability to create topics**: Not a must, but useful when unit testing.

**Comment by oleksiyk** [comment]
> Replace consumer fire & forget emitter with promise or function callback

Thats on top of roadmap

> Compression

Something I have with a lower priority

> Ability to create topics

There is no API call to create a topic. There is a server option `autocreateTopics` (or something like that) which will make Kafka to create a topic when its metadata is first requested but the topic is created with default parameters, which is useless. Unless there will be a specific API call to create/manage a topic I'm against this. You can always call `spawn(kafka-topics.sh..)` in unit tests.

**Comment by ismriv** [comment]
> Thats on top of roadmap

That's great to hear. Would you create an issue and we can elaborate there? Would you take this feature yourself?

> Something I have with a lower priority

I'm happy with kicking off some work around compression, especially snappy since it's the one we currently use.

Regarding creation of topics, fair enough. Not having an API sucks, so I'm actually in favor of not having a function that only _kind of_ works.

**Comment by estliberitas** [comment]
I'm not into source yet, guys.

Another thing is buffering of requests. Is it already implemented or to be done. I guess it would require changes in `Client`.

**Comment by oleksiyk** [comment]
> Another thing is buffering of requests.

Which exactly requests? Kafka protocol is all about bulk operations so I really don't see any need in additional buffering. Producer.send() allows you to send multiple messages at once. Its very easy to buffer them in your own code and then send a bulk of messages each second or however you like. 

BaseConsumer also groups all fetch requests in one large bulk fetch request.

Am I missing something?

**Comment by estliberitas** [comment]
Ouch, sorry. Batching.

**Comment by oleksiyk** [comment]
> Would you take this feature yourself?

Yes, I would take "Replace consumer fire & forget emitter with promise"  myself. I will open an issue soon.

**Comment by estliberitas** [comment]
Correct, I was talking about batching - 0.9.x docs have these settings: `batch.size` and `linger.ms`. It's not something super-important to me ATM, but still would be good to have. I could take this.

**Comment by ismriv** [comment]
Batching is also interesting, not crucial either for me yet, but if @estliberitas takes that one, it would be great.

An interesting use case for buffering though is when the broker is temporarily unreachable, like when doing a rolling maintenance for example. As far as I know, the current producer will try 3 times now, with 1 second interval, which may not be enough to discover the new leader. The guys at Uber implemented something in these lines in a non-maintained Kafka driver, where you could say the limit in time and/or messages allowed to be buffered before erring.

**Comment by oleksiyk** [comment]
Right, 3 times but with increasing delay, for a total of 6 seconds. This can probably be moved to options.

**Comment by estliberitas** [comment]
Better to move to options, really, coz otherwise someday we may run into situation like with node-zookeeper-client, where reconnection is handled so internally so in fact you can't affect it's behavior.

**Comment by estliberitas** [comment]
Alright, I will work on batching this weekend or more probably start of next week.

**Comment by estliberitas** [comment]
Btw, @carlessistare @paddy3883 @jfkoch are you interested in participating, guys? :wink:

**Comment by jfkoch** [comment]
@estliberitas count me in. Should we move this conversation to a different forum?

**Comment by estliberitas** [comment]
@jfkoch Well it's already different forum ))

**Comment by paddy3883** [comment]
Yes count me in too!

**Comment by estliberitas** [comment]
@jfkoch Good idea, but I don't think it's time for this yet. We here are not like discussing adding promises to Node.js core (Github trims that discussion afaik already, very big amount of messages).

**Comment by carlessistare** [comment]
@estliberitas yes I am interested in participating, even if I am not yet much into to code.
If you take the producer batch feature you may be interested in taking a look into my 2 pr's (one merge, and the other pending) for kafka-node https://github.com/SOHU-Co/kafka-node/pull/262 https://github.com/SOHU-Co/kafka-node/pull/314
That said, is there any other priority feature, I could take car of?

**Comment by estliberitas** [comment]
Hi, guys. I've got a bit too busy on these business days. Will work on batching this weekend for sure.

**Comment by oleksiyk** [comment]
Actually, I'm going to start on batching as well. So probably no reason for you.

**Comment by oleksiyk** [comment]
Once its complete it will go to 2.0 branch. There are some minor bugs pending and then I'm ready to release 2.0.

**Comment by estliberitas** [comment]
Okay. Btw, did you test gzip compression under big load? Event loop tick avg time would make a sense.

**Comment by oleksiyk** [comment]
> Btw, did you test gzip compression under big load?

Not yet. What kind of problem to expect?

>  Event loop tick avg time would make a sense.

What does that mean?

**Comment by estliberitas** [comment]
Since Node runs JS in 1 thread, when you call many `*Sync()` methods and especially if they do a lot of computation you'll block JS thread. So, since Node is based on `libuv`'s event loop all the calling synchronous methods blocks current event loop tick. So timers don't fire, connections are not accepted while JS is executed (timers are executed in the start of event loop, all the async i/o enters JS environment then, and `setImmediate()` fires after all of that if I recall correctly). This is a big price you pay if you do too much sync computation in Node. 

This means any other business logic requiring fast interaction (websocket keep-alives, usual HTTP requests maybe) may be affected and start returning timeouts or similar errors.

**Comment by oleksiyk** [comment]
Yeah, I understand that. But all buffers already received. It doesn't matter if you call ungzip() and wait for callback or call ungzipSync(). Same buffer will be processed the same sync way in zlib. It will only matter if you wait for more buffers to arrive from socket or file handle for example.

**Comment by estliberitas** [comment]
The only difference is that ungzip would execute in one of 4 (default) libuv i/o threads and ungzipSync() - in js

**Comment by oleksiyk** [comment]
I'm happy to provide two ways for compression, sync and async. I suspect sync will be much faster for smaller Kafka messages (and/or large number of partitions for topic). Async might be better if compressed messages exceed some (>200KB?) size. 

It would be nice to have a benchmark suite. Interested in creating one?

**Comment by estliberitas** [comment]
Sure.

**Comment by oleksiyk** [comment]
Great! 
Please select 2.0 branch as target for PR

**Comment by oleksiyk** [comment]
Both sync and async compressions are now supported: https://github.com/oleksiyk/kafka/commit/c3a23781cef79ff5aaf42643d1f8eb065c26d3f0

with the `asyncCompression` boolean option.

**Comment by estliberitas** [comment]
Hi guys. Sorry that did not notify earlier. I'm a bit out of game for some time because of relocation process.

**Comment by tizzo** [comment]
So where does this leave stewardship for this module? Should new features probably target this repo or the original?

**Comment by estliberitas** [comment]
@tizzo it's actually original, it's up to you what to work on
