### ISSUE TITLE
Is Simple Consumer same as the old Kafka Simple consumer

### ISSUE THREAD

**Issue by goodfella1408** [oleksiyk/kafka#123]
There are two types of consumers documented - simple consumer and group consumer
Is the simple consumer same as the old Kafka simple consumer or is it the old high level consumer .
Seeing that we can pass group id to the simple consumer and also the description ("Suitable for simple use cases") one is  tempted to think it's the old high level consumer  but if one goes by the name it seems to be the old simple consumer
Do we have to handle broker leader changes if it is the old Kafka simple consumer ?
I think it would be good if the wiki calls it out explicitly whether the simple consumer is indeed the old kafka simple consumer

**Comment by oleksiyk** [comment]
SimpleConsumer is old Kafka Simple Consumer.
