### ISSUE TITLE
Lodash merge causing chaos with messages

### ISSUE THREAD

**Issue by eastlondoner** [oleksiyk/kafka#124]
Lodash released an update 2 days ago which I think is causing this problem that I see on new npm installs.

I have step-through debugged and following the call to _.merge in _mapTopics (client.js) on FetchResult the messages in messageSet change from UInt8Arrays of appropriate length (e.g.42) to UInt8Arrays of size 8192 - which appear to contain the entire message from the server.

I think this is because _.merge has changed to iterate the buffer in a dodgy way

The result is that the resulting message.value (and message.key) are completely wrong. All my tests which were passing previously fail catastrophically.

**Comment by eastlondoner** [comment]
To reproduce:

npm cache clear
rm -rf node_modules/lodash/
npm install lodash@4.15.0

now run tests against no-kafka

**Comment by eastlondoner** [comment]
I am pretty sure it's caused by this:
https://github.com/lodash/lodash/commit/4a4e54479a6eecd916a0e39d400c54bcbba51c31

**Comment by eastlondoner** [comment]
SEE: https://github.com/lodash/lodash/issues/2707

**Comment by oleksiyk** [comment]
It happens quite often with `_.merge`

I've fixed lodash at version 4.5.0. Published as 2.8.3
