### ISSUE TITLE
No Kafka support for confluent kafka 0.10

### ISSUE THREAD

**Issue by avichopra1989** [oleksiyk/kafka#135]
We are using confluent version of kafka version 0.10. We want to confirm if there is any issue with the latest no-kafka? Do we need to worry about any failures with the latest version of kafka?

**Comment by shaharmor** [comment]
Did you find anything?

**Comment by mohitkhanna** [comment]
@avichopra1989 Did it work?

**Comment by avichopra1989** [comment]
@mohitkhanna @shaharmor It did work.
