### ISSUE TITLE
Support loading SSL Cert/Key directly

### ISSUE THREAD

**Issue by ahamidi** [oleksiyk/kafka#145]
Thanks for rolling out SSL support. We’d like to explore some potential changes that could make no-kafka more flexible though.

In particular the limitation of having to load Certs/Keys from files prevents it from being used on platforms with read-only file systems and in particular cloud/PaaS providers like Heroku (I work at Heroku), IBM Bluemix, Azure etc…

I’d like to propose the following:
```
// Add additional ssl options
var producer = new Kafka.Producer({
  connectionString: 'kafka://127.0.0.1:9093', // should match `listeners` SSL option in Kafka config
  ssl: {
    cert: ACTUAL_CERT_STRING
    key: ACTUAL_KEY_STRING
  }
});
```
This would maintain backward compatibility with the current Cert and Key files, and allow the flexibility of pulling in the Cert and Key strings directly from anywhere (i.e. an environment variable).

This change would also help address #144 and #142.

If you’re happy with the proposed API changes we can submit a PR.

Thanks,

Ali

**Comment by oleksiyk** [comment]
Published as 3.0.2
