### ISSUE TITLE
Inconsistent Version Information

### ISSUE THREAD

**Issue by Joe0** [oleksiyk/kafka#146]
So, in the readme, it says this is a 0.9 Kafka client, but in the .travis.yml, the before-install is using Kafka 0.10. Which version does this really support? Is it safe to use Kafka .10 and this library, and will it cause any issues or annoying logs/errors due to using this library?

**Comment by oleksiyk** [comment]
This library uses version 0.9 of Kafka protocol. It naturally works with Kafka 0.9 and also works with Kafka 0.10 but doesn't support some new features in 0.10. 

As you can see its being tested with 0.10 so there should not be any issues.
