### ISSUE TITLE
Calling producer.send() before producer.init() is keep on throwing errors

### ISSUE THREAD

**Issue by raviten** [oleksiyk/kafka#154]
How to handle them?
If i call producer.init() multiple times, Does it initializes every time?

```
 ERROR no-kafka-client Metadata request failed: RangeError: Input array must contain at least 1 items but contains only 0 items
RangeError: Input array must contain at least 1 items but contains only 0 items
```

**Comment by oleksiyk** [comment]
You should call `init` only once.

**Comment by stephanschielke** [comment]
And you should double-check to call it at all...

Took me a few to find this issue. Thanks for putting the error text in here.
