### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by felixheck** [oleksiyk/kafka#158]
Hi there!

Is there a smart way to check if there is currently a connection to the defined Kafka cluster?
Want to provide a health check endpoint which exposes if there is a connection or not.

Thanks and Cheers!

**Comment by felixheck** [comment]
Does `myProducer.client.heartBeatRequest()` show when there is no connection in the rejection handler?

**Comment by oleksiyk** [comment]
There is no health check for a `SimpleConsumer` or `Producer`. `client.heartBeatRequest()` is for GroupConsumers only. With producers you can send small messages to some topic that no one listens to.

**Comment by felixheck** [comment]
Thanks!
Works so far :)
