### ISSUE TITLE
GroupConsumer.end() never gets resolved/rejected

### ISSUE THREAD

**Issue by matthewchngshopback** [oleksiyk/kafka#159]
I'm trying to gracefully restart the worker by calling `GroupConsumer.end()` but the promise returned from this method never seems to be resolved before node exits.  Not quite sure what I'm doing wrong or if this is an issue.

I have code that looks like so
```
const consumer = new Kafka.GroupConsumer({
  ...
});

const strategies = {
  ...
}

const startConsumer = () => {
  log.info('Connecting to %s...', kafkaBrokersConnectionString);
  consumer.init(strategies);
};

const stopConsumer = () => {
  log.info('De-registering clients from kafka brokers...');
  consumer.end()
    .then(() => {
      log.info('De-registered clients from kafka brokers');
    });
};

startConsumer();
setTimeout(() => stopConsumer(), 10000);
```

Log outputs:
```
Connecting to kafka://...
INFO fashion-service-worker Joined group local.test-worker generationId 109 as test-worker-86052c83-32f3-44ef-a951-4793fc989343
INFO test-worker Elected as group leader
DEBUG test-worker Subscribed to test.topic:0 offset 343679 leader ...:9092
De-registering clients from kafka brokers...
```

Notice that when the process enters the `stopConsumer()` method, `consumer.end()` is called but the following `.then()` portion never print the `De-registered clients from kafka brokers` message thereafter and node exits.

**Comment by oleksiyk** [comment]
This doesn't look like correct use of promises. Using `GroupConsumer.end()` is covered in tests so I don't think there is really something wrong there. Proper code should look similar to:

```javascript
consumer.init(strategies)
    .delay(3000)
    .then(function () {
        return consumer.end();
    })
    .then(function () {
        console.log('ended');
    })
    .catch(function (err) {
        console.log(err);
        process.exit(255);
    });
```

And it actually works as intended.

**Comment by matthewchngshopback** [comment]
Please do correct me if I'm wrong but doesn't `GroupConsumer.end()` return a spec compliant bluebird promise?  If it does, why is `GroupConsumer.end().then(() => console.log('ended'))` a wrong use of promise?

How is this different from your method of chaining?

**Comment by oleksiyk** [comment]
Your `startConsumer` doesn't return a promise, your `stopConsumer` doesn't return a promise. `stopConsumer` is called in `setTimeout`. Thats not how promises are normally used. 
However this is not a reason why log message is not printed. From your piece of code it is simply not clear what else happens in your node process.

**Comment by matthewchngshopback** [comment]
Basically I'm hooking up  `process.on('exit', stopConsumer)` so that when the process is sent a signal that triggers an exit request, it will clean up after itself.

I could do this when exit is triggered but the result is still the same. The final log message doesn't get fired. 
```
Promise.resolve()
  .then(() => {
     return consumer.end();
  })
  .then(() => {
     log.info('De-registered clients from kafka brokers');
  });
```

Thanks anyway, I'll dig deeper and post here if I find my mistake.

**Comment by oleksiyk** [comment]
> Basically I'm hooking up process.on('exit', stopConsumer) 

Look at the docs for `process` `exit` event:

>Emitted when the process is about to exit. There is no way to prevent the exiting of the event loop at this point, and once all exit listeners have finished running the process will exit. **Therefore you must only perform synchronous operations in this handler**.
