### ISSUE TITLE
Suggestion: Provision to configure trust store instead of SSL cert and key

### ISSUE THREAD

**Issue by coder404** [oleksiyk/kafka#161]
Hello,

I am currently using the no-kafka node to build a node-red module to connect to a TLS enabled Kafka cluster. I was happy to find a node that gives an option to connect to a secure Kafka cluster.

It would be great if instead of setting the SSL cert/key we are able to set the path to the trust store. (similar to the arguments passed to kafka-console-producer.sh)

**Comment by oleksiyk** [comment]
I don't think this will be on track as TrustStore is a Java thing.
