### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by jdconley** [oleksiyk/kafka#172]
I am receiving this error with some of my integration tests that bring consumers and producers up and down repeatedly. In my tests, this line throws the error: https://github.com/oleksiyk/kafka/blob/eb17ec05c57ea4e6fa905d1737ba9b7b86eb0a40/lib/client.js#L309

Having looked at the code, there are a few situations where `Client.prototype.updateMetadata()` returns null. There are also places (like client.js line 309) where the consumers and producers assume `updateMetadata()` always returns a `Promise`.

I would think that either `updateMetadata()` should always return a `Promise` (possibly an already resolved or rejected one), or the calling code should be more robust.

**Comment by oleksiyk** [comment]
Thanks, fixed in 3.1.5
