### ISSUE TITLE
supported kerberos?

### ISSUE THREAD

**Issue by yuu2lee4** [oleksiyk/kafka#178]
If supported Kerberos?

**Comment by oleksiyk** [comment]
No, Kerberos is not supported

**Comment by yuu2lee4** [comment]
any plan for it?

**Comment by oleksiyk** [comment]
no plans for now

**Comment by yuu2lee4** [comment]
Maybe could do it based on those modules:
https://github.com/adaltas/node-krb5
https://www.npmjs.com/package/krb5
