### ISSUE TITLE
SASL PLAIN Authentication Support?

### ISSUE THREAD

**Issue by armenthiz** [oleksiyk/kafka#189]
Recently i was following [this](https://developer.ibm.com/opentech/2017/05/31/kafka-acls-in-practice/) to enabled SASL PLAIN security in kafka.

Then, when i want to produce to a topic using this library, im got this respond.
`{ [NoKafkaConnectionError: Kafka server has closed connection]
  name: 'NoKafkaConnectionError',
  server: '127.0.0.1:9092',
  message: 'Kafka server has closed connection' }  `

Is there's a good practice or there are a support for authenticate into kafka enabled sasl plain security?

**Comment by oleksiyk** [comment]
no-kafka library doesn't support Kafka authentication.

**Comment by armenthiz** [comment]
thanks for your respond @oleksiyk, i'll close this issue.
