### ISSUE TITLE
no -kafka with node js behaving inconsistently

### ISSUE THREAD

**Issue by VineetKillerX** [oleksiyk/kafka#199]
Hi,

Facing an issue where the messages from the node are sent but the messages do not arrive to the kafka topic. 

We are using no-kafka and  the following code
producer.init().then(function(){
		   producer.send({ .....data}}

What we are noticing while messages from other sources are reaching the kafka topic messages from this node.js code sometimes reach and some times they dont.  The same message at times is not visible in the comsumer-console and sometimes it is not. 

Issue doesnt seem to be in the kafka. 

Any pointers will greatly help.

**Comment by oleksiyk** [comment]
Check the producer response, it should contain errors if any topic/partition pair failed.

**Comment by VineetKillerX** [comment]
Response is coming null on success as well as error scenarios.

**Comment by oleksiyk** [comment]
It can't be `null`, its a promise containing result of produce request: commit offsets or corresponding errors.

**Comment by VineetKillerX** [comment]
while printing the result we are getting undefined in the console log. are we missing something. for both the success(message reaching kafka) and the failure scenario we are getting undefined

producer.init().then(function(){
		   producer.send({
		      topic: "xxx",	      
		      message: {
                  key: key,
		          value: jsonData
		      }
		  });
		})
		.then(function (error,result) {
		console.log("error : "+error);
		console.log("Result : "+result);
         logger.log("debug","Message Successfully produced to Kafka with key :: %s at :: %s",key,new Date().getTime());
			callback(null, constants.SUCCESS_STATUS_CODE);
		})
     .catch(function(err){
        logger.log("error","Error Occurred while producing to Kafka :: %s with key :: %s, topic :: %s ",err,key,topic);
         callback(constants.FAILURE_STATUS_CODE,null);
     });

**Comment by oleksiyk** [comment]
You should pay attention to your use of Promises, there are multiple errors in your code. 

You are missing return statement before `producer.send`. 

`then(function(error, result)` should read `then(function(result)`.

**Comment by VineetKillerX** [comment]
Hi,
After doing changes as recommended by you, we were able to notice that NoKafkaConnection Error is being thrown for the first 2-3 times when application is idle. After 2-3 times, the Connection is established and all the other subsequent requests are getting produced to Kafka.

Please check the Producer Config .

var producer = new Kafka.Producer({	
	requiredAcks: "1",
	connectionString: "xxxxxx",
    timeout : 3000,
    connectionTimeout: 3000,
    socketTimeout: 1000,
    reconnectionDelay:{
        min: 3000,
        max: 10000
    },
    retries:{
        attempts : 2,
        delay  : 3000
    },
	batch : {
		size : 16384		
	}  
});
