### ISSUE TITLE
Init producer just one time

### ISSUE THREAD

**Issue by arturogalan** [oleksiyk/kafka#205]
Hi!, I see on documentation that you call init() method each time you want to send a message to a topic: 

```javascript 
return producer.init().then(function(){
  return producer.send({
      topic: 'kafka-test-topic',
      partition: 0,
      message: {
          value: 'Hello!'
      }
  });
})
```
What could be the best way to call init() method just once in a node program? As this method returns a Promise, I can't call it on the module.exports code block.

Thanks!

**Comment by oleksiyk** [comment]
You call `init()` and then you send messages or do whatever you need. It would be absolutely incorrectly to call `init()` each time you want to send a message.

**Comment by arturogalan** [comment]
I know that it's absolutely incorrectly, that's exactly the reason I'm asking you, if I have a node.js server that it's always listening and sending messages to kafka I cannot call just once to your init method because it's a promise, so I don't have a synchronous method to init the producer in the start process of this server.
I cannot call init in a node module, because Modules in Node that you load with require() are loaded synchronously.


Do you know what  mean?

**Comment by hugebdu** [comment]
@arturogalan 
```js
let producer = new kafka.Producer(...);
producer.init()
	.then(() => initMyHttpServerThatUsesInitializedProducerProvidedHere(producer));
```

**Comment by ngmikeng** [comment]
> You call `init()` and then you send messages or do whatever you need. It would be absolutely incorrectly to call `init()` each time you want to send a message.

I think the examples maybe make misunderstand and using that in a loop could lead to memory leak issue, it would be great if we clarify this on document.
