### ISSUE TITLE
NokafkaConnectionError - Connection Timeout 

### ISSUE THREAD

**Issue by arpanimage** [oleksiyk/kafka#210]
If I get a no connection timeout error then does that mean that the request from node server has reached Kafka servers. 

Is there a possibility that connection timeout can occur when the request has not left node server? Id so what could be the reason for this.

**Comment by oleksiyk** [comment]
It can be both, its an underlying network timeout. It can be TCP socket timeout for example and it might actually happen somewhere on the route from Node server to Kafka server. I suggest you use tcpdump or similar tool to analyse your network connection.
