### ISSUE TITLE
Kafka server has closed connection

### ISSUE THREAD

**Issue by VineetKillerX** [oleksiyk/kafka#212]
Hi,
Facing some issue while producing to Kafka from no-kafka producer.
The issue being - The messages are getting produced to Kafka and are successfully processed at the back end as well but from the no-kafka client I am getting an error object which is as below : 

Error Occurred while producing to Kafka for topic :: XXX with key as :: XXX . The Error is :: {"name":"NoKafkaConnectionError","server":"some server name","message":"Kafka server has closed connection"}

Below is the sample code from where we are getting this Log:

exports.kafkaWriter= function(topic, key, jsonData, callback){
	 producer.init().then(function(){
		   return producer.send({
		      topic: topic,	      
		      message: {
                  key: key,
		          value: jsonData
		      }
		  });
		})
		.then(function (result) {
		logger.log("debug","Result Obtained from Producer : %s",JSON.stringify(result));
		if(result[0].error==null){
        logger.log("debug","Message Successfully produced to Kafka with key :: %s at :: %s and Result :: %s",key,new Date().getTime(),result);
			callback(null, constants.SUCCESS_STATUS_CODE);
			}else{
			**logger.log("error","Error Occurred while producing to Kafka for topic :: %s with key as :: %s . The Error is :: %s",topic,key,JSON.stringify(result[0].error));**
				callback(constants.FAILURE_STATUS_CODE,null);
			}
		})
     .catch(function(err){
        logger.log("error","Error Occurred while producing to Kafka :: %s",err);
         callback(constants.FAILURE_STATUS_CODE,null);
     });	
	 
}

Please Suggest

**Comment by oleksiyk** [comment]
I suggest you look at Kafka server logs for the reason why it has closed connection.
