### ISSUE TITLE
Error handling of consumer data handler

### ISSUE THREAD

**Issue by steffansluis** [oleksiyk/kafka#219]
If I understand the [code](https://github.com/oleksiyk/kafka/blob/eb17ec05c57ea4e6fa905d1737ba9b7b86eb0a40/lib/base_consumer.js#L68) correctly, the handler error is being swallowed there. This causes the consumer to keep running if the handler fails. I think it would be nice to be able to actually have an error thrown there when the handler breaks. Users should still be able to catch that error themselves by wrapping their function logic in a try catch if need be.

**Comment by oleksiyk** [comment]
You should catch and process your handler errors yourself, there cannot be a suitable solution for everyone: one would want to keep running, someone else would want to terminate the process. So just wrap your handler and do what you need.
