### ISSUE TITLE
Bad signature for getPartitionOffset in base_consumer.js line 95

### ISSUE THREAD

**Issue by almodib** [oleksiyk/kafka#224]
Hi Guys,

i want to share with you, an issue that i'm having in my current project.
I got "OffsetOutOfRange" when i was consuming topic from a specific Offset, so i want to handle this by moving to the first Offset in this topic, i set the option for my KAFKA consumer to Kafka.EARLIEST_OFFSET, but my consumer doesn't move to the first offset in case of ERROR "OffsetOutOfRange".
Then i checked in the library code, and found  that there's a bad signature for the function that's setting the parameter.
The function support 4 parameters, while in the library there's 5 parameters, the parameter Time is always set to NULL in that line, so in case of "OffsetOutOfRange", it's always moving to the last offset. 
I'm using library version 3.2.8.

Best Regards.

**Comment by oleksiyk** [comment]
Thanks, fixed in 3.2.9
