### ISSUE TITLE
Lodash dependency is a security vulnerability

### ISSUE THREAD

**Issue by rakeshramakrishnan** [oleksiyk/kafka#227]
Need to update lodash, because of security vulnerabilities: https://nodesecurity.io/advisories/577

**Comment by rakeshramakrishnan** [comment]
Have tried updating lodash locally, but some tests are failing even with the existing lodash version - is there anything else needed to be done apart from having a local kafka server and running `npm run test`?

**Comment by oleksiyk** [comment]
> Need to update lodash, because of security vulnerabilities: https://nodesecurity.io/advisories/577

Thanks, `loadash` updated in version 3.2.10

> Have tried updating lodash locally, but some tests are failing even with the existing lodash version

Which exactly tests?
