### ISSUE TITLE
If consumer group Id is wrong not throwing any error 

### ISSUE THREAD

**Issue by ashwinismath** [oleksiyk/kafka#242]
Hi,

I am working on GroupConsumer concept if i pass wrong consumer group id it's not throwing any error.

Please help me out in this.

**Comment by oleksiyk** [comment]
It shouldn't throw any error. It will just start a new group.

**Comment by ashwinismath** [comment]
Hi sir ...If that group is not available in that server , it's trying to search the group in infinite loop .Then it won't come back to called function.Then how to handle it.
