### ISSUE TITLE
Use of Promise.each() inside GroupConsumer dataHandler

### ISSUE THREAD

**Issue by johncmunson** [oleksiyk/kafka#258]
A little background... I'm going through a codebase on a project I joined and cleaning up some tech debt.

In this codebase, a GroupConsumer is being used, but I noticed the setup isn't at all like what's shown in your [example](https://github.com/oleksiyk/kafka#groupconsumer-new-unified-consumer-api).

Here's your example...
```js
var dataHandler = function (messageSet, topic, partition) {
    return Promise.each(messageSet, function (m){
        console.log(topic, partition, m.offset, m.message.value.toString('utf8'));
        // commit offset
        return consumer.commitOffset({topic: topic, partition: partition, offset: m.offset, metadata: 'optional'});
    });
};
```

and here is the pattern we are using...
```js
var dataHandler = function (messageSet, topic, partition) {
  messageSet.forEach(m => {
    somePromiseFn(m)
      .then(() => {
        consumer.commitOffset({topic: topic, partition: partition, offset: m.offset, metadata: 'optional'})
      })
      .catch(handleErr)
  })
}
```
The questions I have...
- Is there a concrete reason we should be using Promise.each(), which waits for each promise to resolve before starting the next, like is shown in you example? Or is it fine that we are starting all Promises in parallel?
- If an error is encountered inside of Promise.each() and it isn't handled, it will cause Promise.each() to abort, and no further items in messageSet will be processed. So, should the error be handled locally, or should it be allowed to bubble up?
- In your example, commitOffset(...) is returned inside Promise.each(), and then Promise.each() itself resolves to an array of commitOffset results. This ends up being the return value of dataHandler. Our dataHandler has no return value. Do you see any downside to this?

Any advice would be greatly appreciated. Great library btw, thank you for all the hard work on it.

**Comment by oleksiyk** [comment]
> Is there a concrete reason we should be using Promise.each(), which waits for each promise to resolve before starting the next, like is shown in you example? 

The reason is `commitOffset`. If you start in parallel it will be possible you will commit offset say 11 while messages with offset 7 are still being processed. And then In case of fatal error or improper shutdown you won't be able to restart at proper offset.

> So, should the error be handled locally, or should it be allowed to bubble up?

Your application should fully handle its own errors. no-kafka doesn't know what to do with application errors.

> Our dataHandler has no return value. Do you see any downside to this?

No problem.

**Comment by johncmunson** [comment]
Thanks so much for the input. Regarding the error handling, we would of course handle the error eventually. I'm just wondering whether it should be handled _inside_ of Promise.each(), or whether it should bubble up and therefore cause Promise.each() to abort. Below is an example of what I'm talking about...
```js
// Option 1: Handle errors locally, allowing Promise.each() to fully iterate through messageSet
var dataHandler = function (messageSet, topic, partition) {
  return Promise.each(messageSet, async function (m) {
    try {
      // await some async work, which might throw an error
      return consumer.commitOffset({topic: topic, partition: partition, offset: m.offset, metadata: 'optional'})
    } catch (error) {
      handleError(error)
    }
  })
}
```
```
// Option 2: Handle errors outside of Promise.each, causing Promise.each to break it's iteration
var dataHandler = async function (messageSet, topic, partition) {
  try {
    await Promise.each(messageSet, async function (m) {
      // await some async work, which might throw an error
      return consumer.commitOffset({topic: topic, partition: partition, offset: m.offset, metadata: 'optional'})
    })
  } catch (error) {
    handleError(error)
  }
}
```
My apologies, I realize these are more general Kafka topics I'm trying to understand and not necessarily specific to your library.

**Comment by oleksiyk** [comment]
I prefer to commit offset only if message was successfully processed. 
I prefer that application be designed in such way that in case of error that bubbled up to no-kafka message handler it must report the problem to the monitoring and maybe even exit because its definitely something very serious happened.
