### ISSUE TITLE
Promise.map() without "return"

### ISSUE THREAD

**Issue by jeanmatthieud** [oleksiyk/kafka#26]
Version: 2.0.1
Use-case: using SimpleCustomer to receive events
Platform: Windows
Kafka: 0.9.0

Stack-trace:
Warning: a promise was created in a Promise.map handler but was not returned from it
    at [...]\node_modules\no-kafka\lib\base_consumer.js:69:23
From previous event:
    at d:\dev\attractions-reboot.git\attractions-service\node_modules\no-kafka\lib\base_consumer.js:59:28
    at processImmediate [as _immediateCallback] (timers.js:383:17)

It seems like base_consumer.js:69 sould be prefixed by a "return"

**Comment by oleksiyk** [comment]
Thanks. 

`return` is omitted intentionally as we need to continue fetching other topic/partitions pairs while the user supplied handler is working.

This warning is only shown when node runs with NODE_ENV=development

I'll silence that warning.
