### ISSUE TITLE
Support for Keyed Messages in Producer

### ISSUE THREAD

**Issue by ismriv** [oleksiyk/kafka#29]
The current Producer doesn't support Keyed Messages. We use log compaction in a number of topics, and this would prevent us from fully moving to the new driver. Is this feature in the roadmap?

Great improvements in the last weeks @oleksiyk!

**Comment by oleksiyk** [comment]
Sorry, what do you mean it doesn't support keyed messages?

```javascript
producer.send({
            topic: 'kafka-test-topic',
            partition: 1,
            key: 'test-key',
            message: {
                value: new Date().toISOString()
            }
        }),
```

**Comment by ismriv** [comment]
That's wonderful news then. Neither the documentation nor the unit tests had any mention of it. I should have looked at the source code: https://github.com/oleksiyk/kafka/blob/master/lib/producer.js#L131. Sorry about that!

**Comment by oleksiyk** [comment]
I just didn't consider this as standalone feature. Will add a separate docs and tests items.
