### ISSUE TITLE
group consumers getting the same messages

### ISSUE THREAD

**Issue by nybble73** [oleksiyk/kafka#30]
I was trying this out - running the group consumer example in the README.md, so the default round-robin strategy. Running the consumer in two different processes - the console messages seem reasonable, joining and electing leaders. But pushing messages through tends to show up in both consumers - is this expected?

**Comment by oleksiyk** [comment]
No, this is not expected behaviour. Can you please share the logs of both consumers?

**Comment by nybble73** [comment]
So - this behaviour seems to come about after a bit of shutting down and restarting the consumer processes. It's not predictable, as far as I can tell, but given enough tries I can always get it to happen. I've included in the gist logs from the two consumers from their last start.

https://gist.github.com/nybble73/7e43ae08752caf47e8d9

**Comment by oleksiyk** [comment]
Thanks!

**Comment by nybble73** [comment]
This is great! Looks like it's working perfectly now. Thank you!
