### ISSUE TITLE
Batch commiting

### ISSUE THREAD

**Issue by kkogan** [oleksiyk/kafka#31]
I see you updated the docs to suggest not using Promise.map on a messageSet in the Group Consumer handler (1a63120), but the commitOffset method signature still allows for an array of commits. 
```
/**
 * Commit (save) processed offsets to Kafka
 *
 * @param  {Object|Array} commits [{topic, partition, offset, metadata}]
 * @return {Promise}
 */
GroupConsumer.prototype.commitOffset = function (commits) {
    var self = this;
    return self.client.offsetCommitRequestV2(self.options.groupId, self.memberId, self.generationId,
        self._prepareOffsetRequest('commit', commits));
};
```
Is it not safe, or otherwise undesirable, to batch commit the entire messageSet in the handler function for the same reason you suggest not doing concurrent commits of individual messages?

**Comment by oleksiyk** [comment]
I don't think so. Even if I change this method to accept a single commit only it won't make an application code more safe in any way. The reason this method allows an array of commits is that the Kafka protocol allows it. no-kafka is a middleware, it shouldn't make protocol design decisions.

**Comment by kkogan** [comment]
Ok thanks for the input!
