### ISSUE TITLE
Auto create topic

### ISSUE THREAD

**Issue by yidinghan** [oleksiyk/kafka#32]
Does there is any plan or possibility that `no-kafka` could support `auto.create.topic` like the old time?

**Comment by oleksiyk** [comment]
There is no API call to create a topic. Mentioned server option will make Kafka create a topic when its metadata is first requested but the topic is created with default parameters, which is useless. Unless there will be a specific API call to create/manage a topic I'm against this.

**Comment by yidinghan** [comment]
Yeah, I have looked at to document, and nothing methods about create the topic.
But as you say

```
create a topic when its metadata is first requested
```

Consider as developing convenient, if topic can auto create by this way should be good thing also.
We deploy `Kafka` in the dev machine, so developer could directly developing and testing in local without worry about `Kafka` and `Zookeeper` things.

**Comment by oleksiyk** [comment]
There is no way to be notified when the topic has been created, so the library will need to ping the server with some interval. There is also no way to be notified of any error for this operation. That said, having no guarantees, I'm really not keen on adding this method to the library.

**Comment by yidinghan** [comment]
Enen, I got the point.

  

> On Mar 3 2016, at 3:42 pm, Oleksiy Krivoshey
&lt;notifications@github.com&gt; wrote:  

>

> There is no way to be notified when the topic has been created, so the
library will need to ping the server with some interval. There is also no way
to be notified of any error for this operation. That said, having no
guarantees, I'm really not keen on adding this method to the library.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/oleksiy
k/kafka/issues/32#issuecomment-191633721).![](https://github.com/notifications
/beacon/AINy3JMsYCVr4YmkRIlB61s-IhI5IXU6ks5pppDQgaJpZM4HoKoT.gif)

**Comment by ismriv** [comment]
@yidinghan it's simple enough to implement on your end if really needed. For example:

    var _ = require('lodash');
    var retry = require('retry-bluebird');

    // topics is an array of topic names
    function createTopics(topics) {
      function throwIfErrorReturned(result) {
        var firstError = _.find(_.map(result.topicMetadata, 'error'), _.isError);
        if (firstError) {
          throw firstError;
        } else {
          return result;
        }
      }

      return retry({max: 5, backoff: 200}, function () {
        return kafkaClient.metadataRequest(topics).then(throwIfErrorReturned);
      });
    };

**Comment by yidinghan** [comment]
@ismriv I also seen that `metadataRequest` yesterday, but still thx for offering a good example.

**Comment by oleksiyk** [comment]
https://issues.apache.org/jira/browse/KAFKA-1694

It can land to 0.10.0.0 as per https://cwiki.apache.org/confluence/display/KAFKA/Release+Plan+0.10.0
