### ISSUE TITLE
Reuse same Client instance

### ISSUE THREAD

**Issue by Multiply** [oleksiyk/kafka#35]
Would it be possible to implement the solution to reuse the Client instance between Consumer and Producers?

For example, right now I'm looking at the `topicMetadata` and need that before I can make one of my Consumers, so I thought it'd be nice to simply make a new Client, wait for it to init, and grab the metadata, and then reuse the same client for my new Consumer.

**Comment by oleksiyk** [comment]
This will be a source of various problems and conflicts. The Client instance keeps track of current correlationId, groupCoordinators, broker connections. So if a consumer and/or producer will share the same client instance they will definitely run into the conflicts.

**Comment by Multiply** [comment]
I opted to simply use multiple clients for now, so that might be good. I assumed everything was isolated nicely, so reusing connections wouldn't be too troublesome. You can close this, if it's not on the board or a wishlist. :)
