### ISSUE TITLE
Use of 'strategy' on GroupConsumer

### ISSUE THREAD

**Issue by codyhazelwood** [oleksiyk/kafka#36]
I'm working on porting my application from kafka-node to no-kafka.  So far everything has been much easier to use.  Thanks!

I'm a little uncertain what the `strategy` property of the GroupConsumer init is for.  I've looked through the tests and code a little bit, and it looks like it is just used as a key when storing multiple consumer strategies and handlers, but all of the tests use `'TestStrategy'`.  It would be a nice addition to the docs to explain what this is for.

**Comment by oleksiyk** [comment]
It is the name of the strategy. Kafka server will select the strategy (by name) that is supported by all consumers trying to join the group. This name can be used for backward compatible strategy upgrades, e.g. when you add new strategy under different name (such as 'TestStrategy_v2') but you also leave old strategy. Only when all consumers are restarted, the new strategy will (can) be selected and used.

**Comment by oleksiyk** [comment]
There was an explanation somewhere in Apache Kafka docs but I can't find it right now.

**Comment by codyhazelwood** [comment]
Thanks.  It's not explained in much detail, but I found some info at [http://kafka.apache.org/documentation.html](url) at `partition.assignment.strategy` about halfway down the page.
