### ISSUE TITLE
logFunction implementation

### ISSUE THREAD

**Issue by Multiply** [oleksiyk/kafka#37]
I've tried a few things, and can't seem to find anywhere this is implemented with the simple logger.

Would it be possible to use something like winston, or bunyan, and simply just give it the logger object, rather than a logger function?

**Comment by oleksiyk** [comment]
Thats because its *simple* logger :) 
You can only overwrite a function. However your customised function can call your own winston or bunyan object, why not?

**Comment by Multiply** [comment]
What I meant to write, is that it's not using the logFunction that I give it. I tried what you mentioned, but it's still using the simple logger.

**Comment by oleksiyk** [comment]
The following code works perfectly for me:


```javascript
var consumer = new Kafka.SimpleConsumer({
    logger: {
        logFunction: function () {
            console.log(arguments);
        }
    }
});
```

**Comment by oleksiyk** [comment]
Feel free to reopen this if there is a bug or it doesn't work as advertised
