### ISSUE TITLE
Group consumer question

### ISSUE THREAD

**Issue by riaan53** [oleksiyk/kafka#38]
Hi,

Im playing around with this lib but im not sure how the group consumers are supposed to work. Is it just to group a few partitions based on the selected  strategy? 

How can I round robin one producer over multiple consumers? Must I increment the partition after every message on the producer side?

Thank you!

Regards,
Riaan

**Comment by oleksiyk** [comment]
It depends on the application needs. One application may require that messages with specific criteria (such as message.key) always go to specific partition. Another application may just use random or round-robin partition assignment in producer. 
Same applies to the consumers. All consumers in a single group will split topic partitions between them according to partition assignment strategy. Again, one application may require that a consumer running on serverXX always processes messages from specific partition(s) cooperating with the producer. Another application just wants to split the load (bandwidth of messages). 

This is actually not the feature of the no-kafka library, it is a feature of the Kafka itself. You should probably look for use cases and documentation on Kafka website:  https://kafka.apache.org/documentation.html

**Comment by riaan53** [comment]
thank you @oleksiyk its a bit clearer now. I will check out the docs.

**Comment by oleksiyk** [comment]
For a simple round-robin you can increment the partition number.
Or use Math.rand() for random. 
Or calculate the crc of message contents or message key and then `return crc % partitions.length`
