### ISSUE TITLE
Updating offset because of OffsetOutOfRange after every handler call

### ISSUE THREAD

**Issue by TomaszKasowicz** [oleksiyk/kafka#39]
Hi Oleksiyk

I've been using no-kafka for couple of months and by far this is the best npm package for kafka.
I've recently switched to 2.2.1 and noticed one small issue with base_consumer (used as SimpleConsumer).

Each time dataHandler is invoked i receive a warning **"Updating offset because of OffsetOutOfRange"**
It's probably nothing but I checked that since 2.2.1 I don't have to add +1 to offset when subscribing to kafka partition.
I noticed that +1 is still used in finally() handler in base_consumer::_fetch.

If this is not an issue then sorry for trouble.

Thanks for the great work
Tomasz

**Comment by oleksiyk** [comment]
Can you please share your handler code? Offset increment is there since library creation, its not something that changed in 2.2.1

**Comment by TomaszKasowicz** [comment]
Hi.

It turns out in one of the services which was using no-kafka was a small issue introduced by my colleague (m.offset was preincremented before storing to different variable).

I'm very sorry for trouble and I'm closing the issue.
Thanks You again
Tomasz

**Comment by oleksiyk** [comment]
no problems!
