### ISSUE TITLE
No initial hosts to connect

### ISSUE THREAD

**Issue by mllanes** [oleksiyk/kafka#43]
Connection string needs to be now kafka://host:port otherwise it fails in parsing the host and port:

lib/client.js
`
    self.initialBrokers = self.options.connectionString.split(',').map(function (hostStr) {
        var parsed = url.parse(hostStr);
        var config = {
            host: parsed.hostname,
            port: parsed.port
        };

        return config.host && config.port ? new Connection(config) : undefined;
    });

`

**Comment by oleksiyk** [comment]
Right. Fixed in 2.4.1
