### ISSUE TITLE
Manually close GroupConsumer

### ISSUE THREAD

**Issue by mllanes** [oleksiyk/kafka#45]
Is there any way to force a consumer to close connection?
Something like what [kafka-node does](https://github.com/SOHU-Co/kafka-node#closeforce-cb-1).
The use case is to be able to capture SIGINT|SIGTERM and close the GroupConsumer before baling.

Thanks!

**Comment by ismriv** [comment]
You can call `kafkaConsumer.end()`

**Comment by oleksiyk** [comment]
`.end()` is available for `Producer`, `SimpleConsumer`, `GroupConsumer` and `GroupAdmin`
