### ISSUE TITLE
Why is the default idleTimeout 1000ms?

### ISSUE THREAD

**Issue by jotto** [oleksiyk/kafka#47]
I was trying to understand why `kafka-node` was consuming faster than `no-kafka` and saw that `kafka-node` doesn't have a delay [between fetch requests](https://github.com/SOHU-Co/kafka-node/blob/96496b63588499ca1ec9133a8078a50f0f5af00c/lib/consumer.js#L93-L100)

yet `no-kafka` [defaults to 1000ms](https://github.com/oleksiyk/kafka/blob/b53f8f26380c019a4a5c55ac9916c3efdbd7b687/lib/base_consumer.js#L12) for its [fetch loop](https://github.com/oleksiyk/kafka/blob/b53f8f26380c019a4a5c55ac9916c3efdbd7b687/lib/base_consumer.js#L82-L86)

Was there a reason to set the default at 1000ms (seems high)? Can you think of any risks of setting it to 0? (it also looks like the official Java client fetches continuously)

**Comment by oleksiyk** [comment]
It suited my needs better than continuous fetching with zero timeout. 

I also don't see any risks with setting `idleTimeout` to `0`.

**Comment by jotto** [comment]
Thank you @oleksiyk and thank you for maintaining a great library.
