### ISSUE TITLE
No clean way to close client/consumer?

### ISSUE THREAD

**Issue by steve-gray** [oleksiyk/kafka#5]
Hey,

When writing unit tests, there's no obviously documented way to close the consumers. This is fine for how the tests are written for the library itself, but if you're running them as part of a gulp job then the tests will never let the node process exit, because there's callbacks hanging around.

-Steve

**Comment by oleksiyk** [comment]
Use .end() for clean shutdown (producer/consumer).

**Comment by steve-gray** [comment]
Many thanks! :+1:
