### ISSUE TITLE
producer.send function options

### ISSUE THREAD

**Issue by koresar** [oleksiyk/kafka#54]
Thank you for the awesome module supporting so many neat features!

I'm struggling with its API though. It's not clear from the README what are the `producer.send()` function options.

1) The first argument is a `message`. Although, the `message` can have property `message`. So it's unclear what "message" is. Either the first argument, or the property of the first argument.
2) Sometimes it says that it's not `message` but `messages`. I assume, but not sure, that the first argument can be an array.
3) And the most important! The second `options` argument possible properties are not listed anywhere. All I see is the [`Producer` options](https://github.com/oleksiyk/kafka#producer-options). Could you update the README with the `.send` function options please?

Thank you so much

**Comment by koresar** [comment]
Слава Україні :)

**Comment by oleksiyk** [comment]
1) Can you please point me at the place where the first argument to `.send` is called `message`?  

2) First argument to `send` is either a:
- single data structure containing topic, partition, key and message value
- or the array of the above structures

3) Its `codec`, `retries`, `batch` options in the same structure as in Producer constructor.

Its quite easy to get all the answers by looking at the `send` code and its head doc: https://github.com/oleksiyk/kafka/blob/master/lib/producer.js#L129

**Comment by estliberitas** [comment]
@oleksiyk but @koresar is right, there is no description of particular `producer.send()` method unless you want users look into the code. 😉

**Comment by koresar** [comment]
I believe a simple PR would solve the issue for Olexiy. I'll see what I can
do.

**Comment by koresar** [comment]
@olexiyk answering your question. Here it is:
![image](https://cloud.githubusercontent.com/assets/1622575/15096834/58bb2c44-154c-11e6-878c-ac0ceb3fdba0.png)

**Comment by koresar** [comment]
While doing the #56 I realized that the `value` property must be string. Although, I was under and impression that an arbitrary object is acceptable too.

**Comment by oleksiyk** [comment]
I guess you mean the `value` property of the `message` structure? It can be either a String or a Buffer. It is up to the user to transform arbitrary object into the Buffer.
