### ISSUE TITLE
producer with connectionString 'localhost:2121/kafka' can't connect to server

### ISSUE THREAD

**Issue by blackconcerto** [oleksiyk/kafka#55]
My server url is configured with the path like 'localhost:2121/kafka', but I found no-kafka connect the server by net.socket, and only use host and port.
Could you suggest any way to support it?

**Comment by oleksiyk** [comment]
Sorry, your question is not clear. I don't think Kafka has any path part in ints connection settings. Are you sure you are not trying to connect to Zookeeper (which has a path part)?

**Comment by blackconcerto** [comment]
Oh, sorry. Yeah, we use kafka and zookeeper to analyse and admin the nginx access and program module log. Nodejs server as a log producer, i set the connection as:
var producer = new Kafka.Producer({ requiredAcks: 1,connectionString: 'localhost:8888/kafka' });

It get a connection error with the kafka server. In fact, we extend our server with zookeeper. And I found no-kafka dosen't support zookeeper string. In issue [https://github.com/oleksiyk/kafka/issues/46](url) , I find you haven't plan to support it, yet. And I will solve the problem myself by other ways.
