### ISSUE TITLE
Handling long leader election and/or broker outages for the PRODUCER

### ISSUE THREAD

**Issue by jotto** [oleksiyk/kafka#60]
## Steps to reproduce
1. start 2 kafka brokers (ports 9092, 9093)
2. create `mytopic` with replication-factor of 2

     ```bash
     ./bin/kafka-topics.sh --zookeeper localhost --topic mytopic --create --partitions 1 --replication-factor 2
     ```
2. configure `no-kafka` producer with max attempts of 1

     ```javascript
     var producer = new NoKafka.Producer({
       connectionString: 'localhost:9092, localhost:9093',
       clientId: 'producer',
       timeout: 50,
       retries: {
           attempts: 1,
           delay: 50
       }
     });
     ```
3. run `no-kafka` producer in loop

     ```javascript
     setInterval(function() {
       producer.send({
           topic: 'mytopic',
           message: { value: 'value' },
           partition: 0
       })
       .catch(function(err) { console.log('promise rejection', err); })
       .then(function(err) { console.log('promise fulfillment', err.error); });
     }, 1000)
     ```
4. `kill -9` whichever broker is the leader for `mytopic:0`
5. witness the producer loop get into a dead/inert failed state

## Explanation
The simple **consumer**'s [fetch loop](https://github.com/oleksiyk/kafka/blob/067c48dfc7787788120dc2f983286aa9200df248/lib/base_consumer.js#L82-L86) ensures that metadata is updated despite arbitrarily long broker outages.

The **producer**, however, gets into an inert state after a long leader election or broker outage (as in, the outage lasts longer than the default of [3 attempts with 1000ms delay](https://github.com/oleksiyk/kafka/blob/067c48dfc7787788120dc2f983286aa9200df248/lib/producer.js#L13-L16)) in which case the promise is fulfilled with an error `NoKafkaConnectionError` (rather than rejected) and _repeated_ calls to `producer.send` continues to fail (because the metadata is not updated).

If the original broker comes back online, the error, expectedly changes to: `NotLeaderForPartition` (but still as a promise fulfillment rather than promise rejection)

Do you have any recommendations on how best to handle this? I can think of a few:

* solutions by changing the caller 
  1. merely increase the `attempts` for the producer to something arbitrarily large
  2. update `no-kafka` to reject the promise allowing the caller to decide what to do (reconnect or fail permanently) (or... was it intentional to return the error via the promise fulfillment?) in either case, reconnect or fetch metadata on failure at caller's discretion
* solutions by changing `no-kafka`
  3. update `no-kafka` to apply a throttled metadata update on ALL producer.send's
  4. update `no-kafka` to apply a throttled metadata update on ALL ERROR'D producer.send's (seemingly most sensible)
  5. update `no-kafka` to apply a circuit breaker like pattern on ALL ERROR'D producer.sends

**Comment by jotto** [comment]
I _believe_ my explanation and steps to reproduce are incorrect (if the `attempt` is set to `1` it will never refresh metadata, but if at least `2`, it works).

**I apologize** for the false alarm.

I was/am trying to reproduce the following error scenarios I've **_possibly_** had with no-kafka (it could or probably is related to other parts of our system):

* network partition causing no-kafka to get into an inert/dead state
* `kill -9` a single kafka broker (in a cluster of 3) that takes 14s to restart causes some messages to be lost (the leader election to the remaining to brokers itself seems to have happened in less than 1s so I can't easily assume that the messages were dropped due to exhausted retries)

**Comment by oleksiyk** [comment]
The return value of the `Producer.send` call contains result for multiple topic/partition pairs (because `send` can send multiple messages to different leaders), thats why in your case with just a single message to the dead leader it is being fulfilled with a error response for that leader. 

I think `NoKafkaConnectionError` is a good choice to return in case the broker is not online but the metadata still points at it. The `NotLeaderForPartition` error should be temporary and subsequent requests should succeed. Is this the case with your test?

My suggestion is to increase `attempts` and `delay` to something that makes sense, and not `attempts=1` and `delay=50`. I don't think you can expect Kafka broker to get back within 50ms.

Oh, I was typing this as you closed the issue....

**Comment by oleksiyk** [comment]
Network partitions are important for my use case as well (I'm using no-kafka to connect over a network with mid to high latency), so if you find out any interesting failure scenario - please let me know.
