### ISSUE TITLE
Producer memory leak when connection to Kafka is lost

### ISSUE THREAD

**Issue by jotto** [oleksiyk/kafka#68]
If a producer suddenly loses connection to all brokers: 

1. There's a memory leak - the producer will continue to allocate a `_try` closure for each call to `producer.send`
2. Meanwhile, the client is in a loop for `updateMetadata` (but doesn't throw any errors AKA "reject any promises")

Ideally (and maybe this is already possible), we could subscribe (or catch) to those failures after a circuit breaker pattern has been tripped and then stop calling `producer.send`

OR... the `producer.send` would reject a promise after the circuit breaker has been tripped (might be the simplest and most intuitive).

If we don't have a mechanism for subscribing to connection failures, our `no-kafka` processes are just going to hit the VM memory limit until the broker(s) is/are available again.

**Comment by oleksiyk** [comment]
I think I'll just add a maximum wait timeout for metadata requests. The client will keep trying but `producer.send` calls will be rejected.

**Comment by oleksiyk** [comment]
Or limit maximum number of attempts: https://github.com/oleksiyk/kafka/blob/3.0/lib/client.js#L184

**Comment by oleksiyk** [comment]
Can you please describe your test case in more detail? Actually I don't see any good immediate solution but I also don't think this can easily happen. If the producer looses connection to all brokers it will still have local copy of the metadata so all `send` requests will be sent (attempted) and then correctly retried and/or returned as error. For the client to enter the endless `updateMetadata` loop it should first loose the local copy or hit unknown topic/partition pair. So how do you replicate it?
