### ISSUE TITLE
Low producer request timeout default?

### ISSUE THREAD

**Issue by aheckmann** [oleksiyk/kafka#70]
I'm wondering why the [default producer timeout is set to 100ms](https://github.com/oleksiyk/kafka/blob/master/lib/producer.js#L12). 

This timeout is passed to the client and then on to the [ProduceRequest](https://github.com/oleksiyk/kafka/blob/master/lib/client.js#L290) call. According to the [Kafka Protocol guide](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol) and the [documentation page](http://kafka.apache.org/documentation.html#producerconfigs): 

> The configuration controls the maximum amount of time the server will wait for acknowledgments from followers to meet the acknowledgment requirements the producer has specified with the acks configuration. If the requested number of acknowledgments are not met when the timeout elapses an error will be returned. This timeout is measured on the server side and does not include the network latency of the request.

Returning an error to the client before all brokers ACK may lead developers to manually retry the write and cause data duplication.

The default Kafka setting is 30 seconds. Why set it so low in this driver?

**Comment by oleksiyk** [comment]
It just suited my use case (fire and forget) and I didn't check Java defaults. 

I'm OK to change defaults for version 3.0.
