### ISSUE TITLE
Any plans for LZ4 compression?

### ISSUE THREAD

**Issue by leeliu** [oleksiyk/kafka#71]
In our tests, lz4 is very cpu friendly and allows us to achieve higher throughput than snappy or gzip.

**Comment by oleksiyk** [comment]
Is it officially supported by Kafka already? Last time I checked it they were still testing it.

**Comment by leeliu** [comment]
The documentation at kafka.apache.org doesn't mention it being testing. Searching for lz4 only mentions:

This configuration accepts the standard compression codecs ('gzip', 'snappy', lz4).

**Comment by oleksiyk** [comment]
Their current implementation of LZ4 is using incorrect hash for the frames and thus is not compatible with other LZ4 implementations. Fixed implementation will be used in Kafka 0.10 with v1 messages: https://issues.apache.org/jira/browse/KAFKA-3160

`no-kafka` doesn't utilize just released API version detection (KIP-35) so LZ4 will definitely land after that.

**Comment by shaharmor** [comment]
Hey @oleksiyk, Any chance to get LZ4 support now?

**Comment by shaharmor** [comment]
Bump
