### ISSUE TITLE
GroupConsumer subscribe after init

### ISSUE THREAD

**Issue by marshauf** [oleksiyk/kafka#72]
Hello,

is it possible to subscribe to a topic with the GroupConsumer after the consumer is started?

**Comment by oleksiyk** [comment]
Yes, you can call `subscribe` any time.

**Comment by marshauf** [comment]
I meant subscribing to a new topic within a strategy.

For example:
```js
let consumer = new kafka.GroupConsumer(options);
var strategies = [{
    strategy: 'RoundRobinAssignment',
    subscriptions: [],
    handler: handler,
}];
consumer.init(strategies);
strategies.subscribe(newTopicName);
```

When I call the subscribe function I assume it isn't going to use a strategy and consuming the topic as a group.

**Comment by oleksiyk** [comment]
Ah, I see, you were talking about GroupConsumer. 

With the GroupConsumer you can't subscribe to new topics after it as initialised. You need to create new instance of the consumer.

**Comment by marshauf** [comment]
Ok, that's what I thought. Thank you.
