### ISSUE TITLE
Group consumer silently fails if message size exceeds max bytes

### ISSUE THREAD

**Issue by jayco** [oleksiyk/kafka#74]
I came across this issue when initially setting up the group consumer. If the message size is larger than the consumers max bytes then the consumer will silently fail without error and stuck on the same offset.

The kaka-console client throws an error `MessageSizeTooLargeException` and appears to adjust the offset allowing for the next message to be processed. 

While obviously having both the consumer and producer running the same max bytes is the logical and correct way to set up, I believe that it could be beneficial for such errors to be passed on from the client.

**Comment by oleksiyk** [comment]
Confirmed
