### ISSUE TITLE
GroupConsumer starting at tail always

### ISSUE THREAD

**Issue by steve-gray** [oleksiyk/kafka#82]
I've tried setting recoveryOffset to -2 on a GroupConsumer, but I'm noticing that it's no longer working. I'm sure we had this working a few months back when I was last looking at this stuff - has there been a regression @oleksiyk or did I just miss something (I'm getting old :grin:)

For example, when I want to reprocess old events - I now can't because it's always running from the at-startup time tail of the queue and not the start.

**Comment by oleksiyk** [comment]
I'm sure there were no changes to that code. EARLIEST_OFFSET can only work if you really have those old messages in Kafka, make sure they were not deleted by Kafka as part of retention policy cleanup.

**Comment by steve-gray** [comment]
PEBKAC. Confused startingOffset and recoveryOffset.
