### ISSUE TITLE
handlerConcurrency is broken

### ISSUE THREAD

**Issue by shvetsm** [oleksiyk/kafka#86]
Hi Oleksyk, thanks for making this awesome library. We were trying to use handlerConcurrency and I noticed that the promise chain is broken in BaseConsumer.prototype._fetch

I made a PR (https://github.com/oleksiyk/kafka/pull/85) to fix the issue, you can use it, you can make the change yourself or you can tell me that the system functions as designed.

Cheers

**Comment by oleksiyk** [comment]
You are right, thanks! Merged.
