### ISSUE TITLE
Join Group Request Does Not Use Protocol Type?

### ISSUE THREAD

**Issue by Mattenable** [oleksiyk/kafka#87]
Seeing some intermittent InconsistentGroupProtocol errors (defined [here](https://github.com/oleksiyk/kafka/blob/master/lib/errors.js#L30)) and noticed that [the protocol uses a field called ProtocolType](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-JoinGroupRequest)

> The ProtocolType field defines the embedded protocol that the group implements. The group coordinator ensures that all members in the group support the same protocol type. 

also noticed this field might not be getting set (see [here](https://github.com/oleksiyk/kafka/blob/master/lib/client.js#L500))

**Comment by oleksiyk** [comment]
Kafka clients should use 'consumer' protocol type and corresponding data structures: https://github.com/oleksiyk/kafka/blob/master/lib/protocol/group_membership.js#L95

The JoinGroupRequest you mention is a generic message that is also used for Kafka internal protocols.

**Comment by oleksiyk** [comment]
You may receive the mentioned error when you trying to join the same existing `groupId` with different assignment strategies.

**Comment by Mattenable** [comment]
Thanks for the reply. Can you see anything wrong with the code below?

```
const kafkaConsumer = new kafka.GroupConsumer({
    connectionString: config.kafka.connectionString,
    groupId: config.groupId,
    maxWaitTime: config.kafka.maxWaitTime
});

const dataHandler = function(messageSet, topic, partition) {
    console.log('Kafka consumer received messages');
};

const strategies = [{
    strategy: config.kafka.topicName + '_Consumer',
    subscriptions: [config.kafka.topicName],
    handler: dataHandler,
    fn: kafka.RoundRobinAssignment
}];

kafkaConsumer.init(strategies);
```

**Comment by oleksiyk** [comment]
I don't see anything wrong here. However that error is mostly functional, meaning for example that it can occur when you killed the group members and then immediately started new members with different subscriptions or assignment strategies. There might be other reasons. Check with Kafka logs, there might be a hint that explains what happened.

**Comment by johnshumon** [comment]
Following is my consumer:
`const
    /* npm modules */
    appRootDir = require ('app-root-dir').get(),
    Promise = require('bluebird'),
    Kafka = require('no-kafka'),

    /* npm modules */
    config = require (appRootDir + '/config/config.js'),
    log = require (appRootDir + '/log/bunyan.js'),

    consumer = new Kafka.GroupConsumer({
        connectionString: config.zookeeperAddress,
        groupId : config.notificationConsumerGroup,
        minBytes: 1,
        maxBytes: 200,
        startingOffset: Kafka.EARLIEST_OFFSET,

    });


function notificationConsumer (topicName) {

    const dataHandler = function (messageSet, topic, partition) {
        return Promise.each(messageSet, function (m){
            log.info(topic, partition, m.offset, m.message.value.toString('utf8'));
            return ({topic: topic, partition: partition, offset: m.offset});
        });
    };

    const strategies = [{
        subscriptions : [topicName],
        // strategy : new Kafka.WeightedRoundRobinAssignmentStrategy(),
        handler : dataHandler,

    }];

    consumer.init(strategies)
}

module.exports = {
    notificationConsumer    :   notificationConsumer,
    dynamicConsumer         :   dynamicConsumer
};
`


That's how I'm calling it in `server.js` file:
`
var Consumer = require(appRootDir + '/no-kafka/consumergroup.js');
            Consumer.notificationConsumer(config.consumerTopic);
`

But it keeps giving the error:
`
2017-01-26T13:28:54.039Z ERROR no-kafka-client Metadata request failed: NoKafkaConnectionError [localhost:2181]: Kafka server has closed connection
0|exp | { [NoKafkaConnectionError: Kafka server has closed connection]
0|exp |   name: 'NoKafkaConnectionError',
0|exp |   server: 'localhost:2181',
0|exp |   message: 'Kafka server has closed connection' }
`

**Comment by oleksiyk** [comment]
Check Kafka server logs for the exact reason why Kafka server has closed connection.

**Comment by johnshumon** [comment]
It's this config making connection problem:
` connectionString: config.zookeeperAddress`. If I comment out this line and start it connects with no error!

**Comment by johnshumon** [comment]
In production scenario, I have to provide `connectionString`. Also there's nothing in the kafka server log that states why connection is closed. 

Any idea or suggestion how to fix it?

**Comment by oleksiyk** [comment]
So probably your `config.zookeeperAddress` is wrong.  

This line `server: 'localhost:2181',` means you are trying to connect to the port 2181 which is normally Zookeeper port, not Kafka. Kafka is using port 9092 usually.
