### ISSUE TITLE
rewind consumer offset

### ISSUE THREAD

**Issue by marshauf** [oleksiyk/kafka#88]
Hello,
I would like to rewind the consumer offset like it is described there:
https://cwiki.apache.org/confluence/display/KAFKA/FAQ#FAQ-HowcanIrewindtheoffsetintheconsumer?

Is it already possible?

**Comment by marshauf** [comment]
consumer.commitOffset and resubscribing seems to do the trick.

```js
const consumer = new kafka.GroupConsumer(config);
consumer.init(strategies);
consumer.commitOffset({topic,offset});
consumer = new kafka.GroupConsumer(config);
consumer.init(strategies);
``
Is this how I should rewind the consumer offset?

**Comment by oleksiyk** [comment]
Yes, thats the only way for now.

**Comment by marshauf** [comment]
@oleksiyk How do I find out the offset of the last send message when I recover?
Or how do I know how many messages until I reach the latest?

**Comment by marshauf** [comment]
The answer to my own question is:
The relevant documentation can be found here: https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetAPI(AKAListOffset)
Calling ``consumer._offset(leader, topic, partition, time);`` gets the latest message offset.
Which is just a wrapper around client.offset.
To get the current committed offset call ``consumer.fetchOffset(commits);``.
