### ISSUE TITLE
TLS and authentication

### ISSUE THREAD

**Issue by felipegs** [oleksiyk/kafka#89]
Is there any plans to support TLS and authentication?

**Comment by oleksiyk** [comment]
Its ready to try in branch 3.0

**Comment by ghermeto** [comment]
@oleksiyk do you have a timeline for 3.0.0 release?

**Comment by oleksiyk** [comment]
Not yet. There are few thing to try with new Kafka but I don't have time right now.

**Comment by ghermeto** [comment]
Thanks for the heads up @oleksiyk. Will be 3.0 be fully compatible with Kafka 0.9 or it will be target to 0.10 only?

**Comment by oleksiyk** [comment]
@ghermeto It will support both 0.9 and 0.10
