### ISSUE TITLE
Accept Delegate for Logger Activity

### ISSUE THREAD

**Issue by steve-gray** [oleksiyk/kafka#9]
In some cases it's desirable to have a custom/central logging component for an application that allows collection of messages from the external/third-party libraries (such as no-kafka). Suggestion here is to make the constructors of the no-kafka library accept an additional parameter on:

- [ ] GroupConsumer
- [ ] SimpleConsumer
- [ ] Producer
etc

This parameter takes the form of an object with .log/.warn/.debug methods - and then defaults back to nice-simple-logger when no value for this property is passed. This allows consuming code to pass in custom logging handlers, such as:

    const csmr = new GroupConsumer({
        logger: {
              warn: function (msg) {
                      // lorem ipsum     
              }
        }
    });
   
The object should be validated to ensure that all required operations are present as typeof === 'function' and then any missing members should be defaulted to passing through to NSL, allowing only specific types of events to be collected.

**Comment by oleksiyk** [comment]
How about simply overwriting 4 functions on a Kafka object:

```javascript
var Kafka = require('no-kafka');

Kafka.log = function (msg, ...) {}
Kafka.error = function ...
Kafka.warn = Kafka.warning = function ...
Kafka.debug = function ...
```

**Comment by steve-gray** [comment]
That feels slightly unclean, as it'll have side effects outside of the context of the module where I do that. If I had two no-kafka clients running, each with different logging sinks wired up I'd have to do evil things to track-back to which client is originating the log message.

**Comment by oleksiyk** [comment]
Thats right, but not having a global logger will require to pass the logger instance down to client, connection, protocol and so on. This is quite an over complication for such simple logging. I would like to leave it for now until the main functionality is stable enough.

**Comment by oleksiyk** [comment]
As a quick solution I can move logging functions to the Client and bind its `clientId` as a first argument for each invocation of log, error, warn, etc. The log messages then will look like this:
```
2016-01-11T16:50:20.901Z INFO no-kafka-client Rejoining group on RebalanceInProgress
```

`clientId` can be changed in options to producer/consumer

**Comment by steve-gray** [comment]
I'm happy with it as-is until the long term solution rolls through. I'm basically just routing the lower levels of logging out to the 'debug' module.

/**
     * Function for suprressing no-kafka logging.
     * @param {String}  msg     Debug/log message.
     */
    function debugWireup(msg) {
      debug('no-kafka')(msg);
    }

    // Don't override error or warn.
    kafka.log = debugWireup;
    kafka.debug = debugWireup;

**Comment by oleksiyk** [comment]
I moved it to client. I think its good for now as-is. You can differentiate messages from several instances of producer/consumer by providing unique `clientId` in options:

```javascript
var consumer1 = new Kafka.GroupConsumer({
    clientId: 'group-consumer-1'
});
var consumer2 = new Kafka.GroupConsumer({
    clientId: 'group-consumer-2'
});
```
=>

```
2016-01-12T07:41:57.884Z INFO group-consumer-1 ....
2016-01-12T07:41:57.884Z INFO group-consumer-2 ....
```

You can also tune the logging level which should be bitwise OR for the following:

1 - errors
2 - warnings
4 - log (info)
16 - debug

```javascript
var consumer = new Kafka.GroupConsumer({
    clientId: 'group-consumer',
    nsl: {
        logLevel: 7 // filter out debug messages (1 | 2 | 4)
    }
});
```

You can overwrite all (error(), log(), warn(), debug()) or just some of the logger functions:

```javascript
var consumer = new Kafka.GroupConsumer({
    clientId: 'group-consumer',
    logger: {
        log: console.log // overwrite just the .log() method
    }
});
```
