### ISSUE TITLE
Kafka 0.8 Version support

### ISSUE THREAD

**Issue by ankitkothana** [oleksiyk/kafka#91]
Does this library support node 0.8? It would be really helpful if it does.

**Comment by oleksiyk** [comment]
It doesn't. 
It is tested only with 0.10 and 4.4

**Comment by ankitkothana** [comment]
Thanks for the information. Could you provide an example where we do not require to init producer again and again and we can use producer to send messages continuously.

**Comment by oleksiyk** [comment]
Please check producer `retries` option. The producer will retry to send messages configured amount of times with configured delay between attempts. Then it will reject to send these messages but the next call to `send` will do all the same attempts.

**Comment by ankitkothana** [comment]
Thanks. I have checked producer retries option. However I am facing one more issue. Below is snippet of  my code:

`var Kafka = require('no-kafka');

var producer = new Kafka.Producer({
    connectionString : "localhost:9092,localhost:9093"
});

var promise = producer.init();

var logEvent = function(message) {
    return promise.then(function(){
        producer.send({
            topic: 'kafka-test-topic',
            partition: 10,
            message: {
                value: message
            }
        }).then(function(result) {
            console.log("Message sent");
        }).catch(function(err) {
            console.log('promise rejection', err);
        });
    })
};

module.exports = {
    logEvent : logEvent
};`

When I am sending message to a topic or partition that does not exist on broker, it still does not sends exception. Every time I am receiving message sent. What's the issue with the code?

**Comment by oleksiyk** [comment]
You need to check the `result` objet returned from `send` call. It contains a map of results (offset or error) for each topic/partition pair.

**Comment by ankitkothana** [comment]
Thanks buddy. Appreciate quick responses and help
