### ISSUE TITLE
Kafka negative commitoffset

### ISSUE THREAD

**Issue by marshauf** [oleksiyk/kafka#92]
Hello,

Committing an offset of 0 and resubscribing results in receiving messages from (including) offset 1.
Setting the offset to a negative number should invalidate the commit offset but no-kafka seems to stop working. It does not retrieve any messages.

I would like the possibility to recover from offset 0 inclusive, not exclusive.

**Comment by oleksiyk** [comment]
First of all there are three different Kafka offset API versions, V0, V1 and V2. no-kafka uses V0 for SimpleConsumer and V1 for GroupConsumer so please confirm which one you are using. It seems like you are using SimpleConsumer and in this case committing offset is not enough to start fetching from it on next subscribe, you should retrieve stored (committed) offset and supply it in `subscribe` call. In short, you commit processed offsets not the next offset you want to read from.

> Setting the offset to a negative number should invalidate the commit offset

Never heard of this. 

> I would like the possibility to recover from offset 0 inclusive, not exclusive.

Ability to recover from specified offset depends on Kafka server. Kafka won't store your messages (and their offsets) forever.

**Comment by marshauf** [comment]
I use the GroupConsumer and it's client.

When the commit offset is -1 it get's set to 0 but the old value is compared here: https://github.com/oleksiyk/kafka/blob/master/lib/group_consumer.js#L302

I heard about invalid commit offsets here: https://mail-archives.apache.org/mod_mbox/kafka-users/201601.mbox/%3CCAAUywg9kwiJ5kxzbjeubQv6KDV2K07x9XZq4r+mFNGfwgpbVTA@mail.gmail.com%3E

In the end I just would like to reprocess all messages from 0 inclusive. I also tried setting the startingOffset and recoveryOffset to 0 with a negative commited offset. The first message is still from offset 1.

**Comment by oleksiyk** [comment]
With GroupConsumer you commit processed offsets meaning that the library will start reading from next sequential offset next time. You can only re-subscribe to previous offsets with SimpleConsumer.

**Comment by marshauf** [comment]
I got it working with GroupConsumer to read from offset 0 inclusive.

```js
const offset = 0;
const startingOffset = offset;
const recoveryOffset = offset;
const config = {};
yield consumer.commitOffset({
  topic: topicName,
  offset: offset - 1,
});
// 0 does not seem to do anything, setting it to earliest works
// 1 however starts from 1 inclusive
if (startingOffset === 0) {
  config.startingOffset = kafka.EARLIEST_OFFSET;
 } else {
   config.startingOffset = startingOffset;
}
if (recoveryOffset === 0) {
  config.recoveryOffset = kafka.EARLIEST_OFFSET;
} else {
  config.recoveryOffset = recoveryOffset;
}
consumer = new kafka.GroupConsumer(config);
yield consumer.init(strategies);
```

I am sorry that I took your time.

**Comment by mickhansen** [comment]
@marshauf Hitting the `Error reading field 'member_id': String length -1 cannot be negative` issue myself atm, did you work out a fix?

**Comment by mickhansen** [comment]
@marshauf Ping, would love to hear from you :)

**Comment by marshauf** [comment]
I can't help you. I am no longer working on this.

**Comment by mickhansen** [comment]
@marshauf Ah alright, just assumed you found a fix back then since you closed the issue :)
