### ISSUE TITLE
closing connection should stop metadata refresh

### ISSUE THREAD

**Issue by shaharmor** [oleksiyk/kafka#95]
When closing the kafka connection (using `producer.end()`), the `updateMetadata` function call will fail and retry itself forever.

This is the line causing it to retry: https://github.com/oleksiyk/kafka/blob/master/lib/client.js#L159
This causes the node instance to remain open forever and not close.

We should check if the connection is client is closed there i think

**Comment by Mattenable** [comment]
Similarly, when the Kafka host becomes unavailable, a producer.send call will never fail. It will just keep trying to updateMetadata forever and the promise will never return.

**Comment by oleksiyk** [comment]
When `Client.end()` is called the next call to `updateMetadata` will exit because of this condition evaluating to `true`: https://github.com/oleksiyk/kafka/blob/master/lib/client.js#L126

The situation with `producer.send` is intended behaviour.

**Comment by shaharmor** [comment]
It will not even get to that line because it will fail in the metadataRequest: https://github.com/oleksiyk/kafka/blob/master/lib/client.js#L123

**Comment by oleksiyk** [comment]
Well spotted! Thanks!
