### ISSUE TITLE
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /src/node_modules/snappy/build/Release/binding.node)

### ISSUE THREAD

**Issue by delmotte** [oleksiyk/kafka#96]
I try to build a dockerfile with your lib, it doesn't work :+1: 

FROM node:latest
COPY package.json /src/package.json
RUN cd /src; npm install
COPY . /src
CMD node /src/index.js

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /src/node_modules/snappy/build/Release/binding.node)

I tried this solution : http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
but it just doesn't work.

What do I have to do to make this work inside a docker ?

Thanks for your anwser

**Comment by oleksiyk** [comment]
Its a snappy module compilation issues. Try 2.6.0 which makes snappy an optional dependancy.
