### ISSUE TITLE
Discussion: More connections than necessary

### ISSUE THREAD

**Issue by jorgemsrs** [oleksiyk/kafka#97]
Hi!

I'm testing against a set of 3 kafka 0.9 brokers. no-kafka ends up creating 5 connections to them. This comes to the fact that the initial metadata request connections end up being different from the subsequent broken connections and the initial connections are not released.

I think this is not expected behaviour, but am I right?

**Comment by jorgemsrs** [comment]
5 connections because one of the hosts is not a leader of any partition

**Comment by oleksiyk** [comment]
Thats expected behaviour.

**Comment by jorgemsrs** [comment]
Ok. Just to understand the rationale before closing the issue - the lib keeps distinct connections for metadata and actual data, correct?

Is this related to anything I may be missing; is it a design decision?

**Comment by oleksiyk** [comment]
Yes, correct, the library keeps the list of metadata and data connections separate. This is design decision.

**Comment by jorgemsrs** [comment]
Thanks. Closing the issue.
